spring.application.name=BIMA
spring.datasource.url=jdbc:postgresql://localhost:5432/pangawedb
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=makutupora
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true

#Maximum
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


